# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tree Meyer
email:
description: > # this means to ignore newlines until "baseurl:"
  I'm Theresa, a web developer with a penchant for being outside,
  puppies, kittens, tea, and really delicious lattes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://treedledee.github.com" # the base hostname & protocol for your site
twitter_username: treemeyer
github_username:  treedledee
linkedin_username: meyertheresa
# Build settings
markdown: kramdown
